services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: project2_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  users_service:
    image: project2_users_service:latest
    build:
      context: ./users_service
    container_name: project2_users_service
    environment:
      USERS_DB_PATH: /data/users.db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      USERS_RPC_QUEUE: users.rpc
    volumes:
      - users_data:/data
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq

  products_service_1:
    image: project2_products_service:latest
    build:
      context: ./products_service
    container_name: project2_products_service_1
    environment:
      APP_INSTANCE: products-service-1
      PRODUCTS_DB_PATH: /data/products.db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      USERS_RPC_QUEUE: users.rpc
    volumes:
      - products_1_data:/data
    depends_on:
      - rabbitmq
      - users_service

  products_service_2:
    image: project2_products_service:latest
    container_name: project2_products_service_2
    environment:
      APP_INSTANCE: products-service-2
      PRODUCTS_DB_PATH: /data/products.db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      USERS_RPC_QUEUE: users.rpc
    volumes:
      - products_2_data:/data
    depends_on:
      - rabbitmq
      - users_service

  nginx:
    image: nginx:1.27-alpine
    container_name: project2_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - products_service_1
      - products_service_2

volumes:
  users_data:
  products_1_data:
  products_2_data:
